### ISSUE TITLE
:nowait is incompatible with :server

### ISSUE THREAD

**Issue by Compro-Prasad** [eschulte/emacs-web-server#10]
https://github.com/eschulte/emacs-web-server/blob/469cd3bc117bfb8da0c03a2a2fb185e80c81d068/web-server.el#L127

I am using Emacs 27 dev. Removing this line fixes the issue.

**Comment by eschulte** [comment]
What effect will removing `:nowait t` have on versions between 24.3 and 27?

**Comment by arminfriedl** [comment]
It should have no effect.

Seems like `:nowait` together with `:server` was never really a valid combination. According to [Bug#31903](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31903) and [Fix#31903](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=90d95b000c37f7e85096716db96c4a940436f387):

&le; Emacs 25 - `:nowait` is silently ignored if `:server t`
&le; Emacs 26.1 - misleading error message
&ge; Emacs 26.1.90 - error: `:server` is incompatible with `:nowait`

**Comment by eschulte** [comment]
Thanks, hopefully this is resolved now.  Please let me know if not.
