### ISSUE TITLE
POST request content is innaccessible

### ISSUE THREAD

**Issue by jcaw** [eschulte/emacs-web-server#11]
When POST requests are made to the server, it's impossible for a handler to access the request's content unless it's either `x-www-form-urlencoded` or `multipart/form-data`. There's no slot in the `request` that actually holds the content. Only headers are accessible.

This makes generalised POST requests impossible. For example, you can't send a JSON post request to the server because the JSON in the POST body can't be accessed.

Could two slots be added to the "request" object - the content-type, and the raw content - to allow the user to manually parse other types of content? For example, if I have a JSON API, I can check that my header is `application/json` and I can then manually run the raw content through a JSON parser.

**Comment by eschulte** [comment]
Could you submit a pull request adding these slots to the request object?  Otherwise it will likely be a while before I have an opportunity to look into this.

**Comment by jcaw** [comment]
Might be a while before I get a chance to, but yes, happy to do so.
