### ISSUE TITLE
Support using a random port number?

### ISSUE THREAD

**Issue by zbelial** [eschulte/emacs-web-server#25]
Hi
I think using a random port number is a useful feature(actually I need it now :) ), do you also think so? If so, I can post a PR to support it. 
Thanks.

**Comment by eschulte** [comment]
Given that `ws-start` already takes the port as an argument I think it should be easy enough for users to pick a random number themselves and pass that to `ws-start`.

**Comment by amygrinn** [comment]
FYI, passing `t` to ws-start will generate a random port already.
