### ISSUE TITLE
Binding to 0.0.0.0

### ISSUE THREAD

**Issue by lispstudent** [eschulte/emacs-web-server#26]
Hello,

I would like to use emacs-web-serve from our local lan, without  proxy.
 
It is not clear from the documentation if it is possible to bind to 0.0.0.0 so to expose emacs-web-server to a local lan?

Is there a configuration variable one can use?

Thank you.

**Comment by eschulte** [comment]
Passing `:host "0.0.0.0"` to `ws-start` should do it.  Please let me know if that doesn't work.

**Comment by lispstudent** [comment]
On my side, passing `:host "0.0.0.0"` to `ws-start` throws error,

```
(ws-start
 (lambda (request)
   (with-slots (process headers) request
     (ws-response-header process 200 '("Content-type" . "text/plain"))
     (process-send-string process "hello world")))
 9001 :host "0.0.0.0")
```

     error: (wrong-type-argument stringp :host)

I went reading [`make-network-process`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Network-Processes.html) documentation, but it still not clear how to pass `:host "0.0.0.0"`.

I have no errors with, 

```
(ws-start
 (lambda (request)
   (with-slots (process headers) request
     (ws-response-header process 200 '("Content-type" . "text/plain"))
     (process-send-string process "hello world")))
 9001 ":host 0.0.0.0")
```

But I am still unable to bind `0.0.0.0`:

Having applied the above form, server replies fine on `localhost`:

```
$ curl localhost:9001
hello world%   
```

But it errors with,

```
$ curl 10.1.1.31:9001
curl: (7) Failed to connect to 10.1.1.31 port 9001: Connection refused
```

Being my local ip 10.1.1.31:

```
$ ip address show
9: eth0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ether e0:4f:43:e6:6d:d8
    inet 10.1.1.31/24 brd 10.1.1.255 scope global dynamic
       valid_lft 78923sec preferred_lft 78923sec
    inet6 fe80::301f:f728:ac27:81d6/64 scope link dynamic
       valid_lft forever preferred_lft forever
1: lo: <LOOPBACK,UP> mtu 1500 group default qlen 1
    link/loopback 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope global dynamic
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host dynamic
       valid_lft forever preferred_lft forever
```

**Comment by eschulte** [comment]
Notice that before the arguments passed along to `make-network-process` is the optional `log-buffer` argument.  So you have to add a `nil` before the `:host` keyword argument.

Try the following:
```lisp
(ws-start
 (lambda (request)
   (with-slots (process headers) request
     (ws-response-header process 200 '("Content-type" . "text/plain"))
     (process-send-string process "hello world")))
 9001 nil :host "0.0.0.0")
```

**Comment by lispstudent** [comment]
Joy now, thank you!

Even reading carefully that page, it makes one feel silly to have wrongly surmised on the position of `log-buffer`.

Thank you for `emacs-web-server` and the kind help.
