### ISSUE TITLE
web-server.el:78:1:Error: Incompatible place needs recompilation: process

### ISSUE THREAD

**Issue by tumashu** [eschulte/emacs-web-server#6]
I use emacs-git and get the compile error:
web-server.el:78:1:Error: Incompatible place needs recompilation: process

**Comment by eschulte** [comment]
I can't reproduce this problem.  Using the latest from git 25.0.50.2, I have all tests passing (see below).  Could you provide more thorough reproduction information, or look for the problem elsewhere in your setup.

Best,
Eric

    $ emacs --version                      
    GNU Emacs 25.0.50.2
    Copyright (C) 2015 Free Software Foundation, Inc.
    GNU Emacs comes with ABSOLUTELY NO WARRANTY.
    You may redistribute copies of GNU Emacs
    under the terms of the GNU General Public License.
    For more information about these matters, see the file named COPYING.

    $ make check                  
    emacs --batch --execute '(add-to-list (quote load-path) "/home/eschulte/.emacs.d/src/web-server")' -l cl -l ert -l web-server-test -f ert-run-tests-batch-and-exit
    Running 14 tests (2015-01-22 19:51:21-0500)
    curl -s -m 4    localhost:8999/: finished.
       passed   1/14  ws/function-style-handler
    dir: "foo/bar/../../../"
    dir: "foo/bar/../../../tmp/baz"
    dir: "./"
    dir: "/~/pics"
    dir: "~/pics"
    dir: "/pics"
    dir: "../pics"
    dir: "pics"
    dir: ".."
       passed   2/14  ws/in-directory-p
    curl -s -m 4    localhost:8999/a: finished.
    curl -s -m 4    localhost:8999/b: finished.
       passed   3/14  ws/keyword-style-handler
       passed   4/14  ws/parse-another-post-data
       passed   5/14  ws/parse-basic-authorization
       passed   6/14  ws/parse-large-file-upload
       passed   7/14  ws/parse-many-headers
       passed   8/14  ws/parse-post-data
       passed   9/14  ws/removed-from-ws-servers-after-stop
    curl -s -m 4    localhost:8999/: finished.
       passed  10/14  ws/simple-chunked
    curl -s -m 4 --compressed   localhost:8999/: finished.
    curl -s -m 4 --compressed   localhost:8999/: finished.
       passed  11/14  ws/simple-gzip
    curl -s -m 4   -F "message=foo" localhost:8999/: finished.
       passed  12/14  ws/simple-post
       passed  13/14  ws/web-socket-frame
       passed  14/14  ws/web-socket-handshake-rfc-example

    Ran 14 tests, 14 results as expected (2015-01-22 19:51:22-0500)
